name: my_profile
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  sizer: ^2.0.15
  google_fonts: ^5.1.0
  animated_text_kit: ^4.2.2
  url_strategy: ^0.2.0
  flutter_email_sender: ^6.0.1
  http: ^1.1.0
  url_launcher: ^6.1.11
  rive: ^0.7.16
  top_snackbar_flutter: ^3.1.0
  infinite_carousel: ^1.0.3
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
